/* fsousage.h generated by valac 0.16.1, the Vala compiler, do not modify */


#ifndef __FSOUSAGE_H__
#define __FSOUSAGE_H__

#include <glib.h>
#include <fsobasics.h>

G_BEGIN_DECLS


#define FSO_USAGE_TYPE_RESUME_REASON (fso_usage_resume_reason_get_type ())

#define FSO_USAGE_TYPE_LOW_LEVEL (fso_usage_low_level_get_type ())
#define FSO_USAGE_LOW_LEVEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_USAGE_TYPE_LOW_LEVEL, FsoUsageLowLevel))
#define FSO_USAGE_IS_LOW_LEVEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_USAGE_TYPE_LOW_LEVEL))
#define FSO_USAGE_LOW_LEVEL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), FSO_USAGE_TYPE_LOW_LEVEL, FsoUsageLowLevelIface))

typedef struct _FsoUsageLowLevel FsoUsageLowLevel;
typedef struct _FsoUsageLowLevelIface FsoUsageLowLevelIface;

#define FSO_USAGE_TYPE_NULL_LOW_LEVEL (fso_usage_null_low_level_get_type ())
#define FSO_USAGE_NULL_LOW_LEVEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_USAGE_TYPE_NULL_LOW_LEVEL, FsoUsageNullLowLevel))
#define FSO_USAGE_NULL_LOW_LEVEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_USAGE_TYPE_NULL_LOW_LEVEL, FsoUsageNullLowLevelClass))
#define FSO_USAGE_IS_NULL_LOW_LEVEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_USAGE_TYPE_NULL_LOW_LEVEL))
#define FSO_USAGE_IS_NULL_LOW_LEVEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_USAGE_TYPE_NULL_LOW_LEVEL))
#define FSO_USAGE_NULL_LOW_LEVEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_USAGE_TYPE_NULL_LOW_LEVEL, FsoUsageNullLowLevelClass))

typedef struct _FsoUsageNullLowLevel FsoUsageNullLowLevel;
typedef struct _FsoUsageNullLowLevelClass FsoUsageNullLowLevelClass;
typedef struct _FsoUsageNullLowLevelPrivate FsoUsageNullLowLevelPrivate;

typedef enum  {
	FSO_USAGE_RESUME_REASON_Invalid = 0,
	FSO_USAGE_RESUME_REASON_Accelerometer,
	FSO_USAGE_RESUME_REASON_AuxKey,
	FSO_USAGE_RESUME_REASON_Bluetooth,
	FSO_USAGE_RESUME_REASON_Debug,
	FSO_USAGE_RESUME_REASON_FullBattery,
	FSO_USAGE_RESUME_REASON_GSM,
	FSO_USAGE_RESUME_REASON_GFX,
	FSO_USAGE_RESUME_REASON_GPS,
	FSO_USAGE_RESUME_REASON_Headphone,
	FSO_USAGE_RESUME_REASON_LowBattery,
	FSO_USAGE_RESUME_REASON_PMU,
	FSO_USAGE_RESUME_REASON_PowerKey,
	FSO_USAGE_RESUME_REASON_PhoneKey,
	FSO_USAGE_RESUME_REASON_Unknown,
	FSO_USAGE_RESUME_REASON_WiFi,
	FSO_USAGE_RESUME_REASON_RingerSwitch,
	FSO_USAGE_RESUME_REASON_Slider,
	FSO_USAGE_RESUME_REASON_Keypad,
	FSO_USAGE_RESUME_REASON_RTC
} FsoUsageResumeReason;

struct _FsoUsageLowLevelIface {
	GTypeInterface parent_iface;
	void (*suspend) (FsoUsageLowLevel* self);
	FsoUsageResumeReason (*resume) (FsoUsageLowLevel* self);
};

struct _FsoUsageNullLowLevel {
	FsoFrameworkAbstractObject parent_instance;
	FsoUsageNullLowLevelPrivate * priv;
};

struct _FsoUsageNullLowLevelClass {
	FsoFrameworkAbstractObjectClass parent_class;
};


GType fso_usage_resume_reason_get_type (void) G_GNUC_CONST;
GType fso_usage_low_level_get_type (void) G_GNUC_CONST;
gboolean fso_usage_low_level_isUserInitiated (FsoUsageLowLevel* self, FsoUsageResumeReason r);
void fso_usage_low_level_suspend (FsoUsageLowLevel* self);
FsoUsageResumeReason fso_usage_low_level_resume (FsoUsageLowLevel* self);
GType fso_usage_null_low_level_get_type (void) G_GNUC_CONST;
FsoUsageNullLowLevel* fso_usage_null_low_level_new (void);
FsoUsageNullLowLevel* fso_usage_null_low_level_construct (GType object_type);


G_END_DECLS

#endif
