/* plugin.c generated by valac 0.14.2, the Vala compiler
 * generated from plugin.vala, do not modify */

/*
 * Copyright (C) 2009-2011 Michael 'Mickey' Lauer <mlauer@vanille-media.de>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <fsobasics.h>
#include <fsousage.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/ioctl.h>
#include <linux/input.h>
#include <sys/select.h>
#include <time.h>
#include <sys/time.h>
#include <fsoframework.h>


#define LOW_LEVEL_TYPE_KERNEL26_STAYSALIVE (low_level_kernel26_staysalive_get_type ())
#define LOW_LEVEL_KERNEL26_STAYSALIVE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), LOW_LEVEL_TYPE_KERNEL26_STAYSALIVE, LowLevelKernel26_StaysAlive))
#define LOW_LEVEL_KERNEL26_STAYSALIVE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), LOW_LEVEL_TYPE_KERNEL26_STAYSALIVE, LowLevelKernel26_StaysAliveClass))
#define LOW_LEVEL_IS_KERNEL26_STAYSALIVE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), LOW_LEVEL_TYPE_KERNEL26_STAYSALIVE))
#define LOW_LEVEL_IS_KERNEL26_STAYSALIVE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), LOW_LEVEL_TYPE_KERNEL26_STAYSALIVE))
#define LOW_LEVEL_KERNEL26_STAYSALIVE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), LOW_LEVEL_TYPE_KERNEL26_STAYSALIVE, LowLevelKernel26_StaysAliveClass))

typedef struct _LowLevelKernel26_StaysAlive LowLevelKernel26_StaysAlive;
typedef struct _LowLevelKernel26_StaysAliveClass LowLevelKernel26_StaysAliveClass;
typedef struct _LowLevelKernel26_StaysAlivePrivate LowLevelKernel26_StaysAlivePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _LowLevelKernel26_StaysAlive {
	FsoFrameworkAbstractObject parent_instance;
	LowLevelKernel26_StaysAlivePrivate * priv;
};

struct _LowLevelKernel26_StaysAliveClass {
	FsoFrameworkAbstractObjectClass parent_class;
};

struct _LowLevelKernel26_StaysAlivePrivate {
	gint fd;
};


static gpointer low_level_kernel26_staysalive_parent_class = NULL;
extern gchar* sys_power_state;
static FsoUsageLowLevelIface* low_level_kernel26_staysalive_fso_usage_low_level_parent_iface = NULL;
static GType low_level_kernel26_staysalive_type_id = 0;
gchar* sys_power_state = NULL;

GType low_level_kernel26_staysalive_get_type (void) G_GNUC_CONST;
GType low_level_kernel26_staysalive_register_type (GTypeModule * module);
#define LOW_LEVEL_KERNEL26_STAYSALIVE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), LOW_LEVEL_TYPE_KERNEL26_STAYSALIVE, LowLevelKernel26_StaysAlivePrivate))
enum  {
	LOW_LEVEL_KERNEL26_STAYSALIVE_DUMMY_PROPERTY
};
static gchar* low_level_kernel26_staysalive_real_repr (FsoFrameworkAbstractObject* base);
static void low_level_kernel26_staysalive_real_suspend (FsoUsageLowLevel* base);
static FsoUsageResumeReason low_level_kernel26_staysalive_real_resume (FsoUsageLowLevel* base);
void low_level_kernel26_staysalive_onInput (LowLevelKernel26_StaysAlive* self, void* data, gssize length);
LowLevelKernel26_StaysAlive* low_level_kernel26_staysalive_new (void);
LowLevelKernel26_StaysAlive* low_level_kernel26_staysalive_construct (GType object_type);
static GObject * low_level_kernel26_staysalive_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void low_level_kernel26_staysalive_finalize (GObject* obj);
gchar* fso_factory_function (FsoFrameworkSubsystem* subsystem, GError** error);
void fso_register_function (GTypeModule* module);


static gchar* low_level_kernel26_staysalive_real_repr (FsoFrameworkAbstractObject* base) {
	LowLevelKernel26_StaysAlive * self;
	gchar* result = NULL;
	gchar* _tmp0_;
	self = (LowLevelKernel26_StaysAlive*) base;
	_tmp0_ = g_strdup ("<>");
	result = _tmp0_;
	return result;
}


static void low_level_kernel26_staysalive_real_suspend (FsoUsageLowLevel* base) {
	LowLevelKernel26_StaysAlive * self;
	FsoFrameworkLogger* _tmp0_;
	gboolean _tmp1_ = FALSE;
	const gchar* _tmp2_;
	FsoFrameworkLogger* _tmp3_;
	gboolean _tmp4_ = FALSE;
	gint _tmp5_ = 0;
	gint fd;
	FsoFrameworkLogger* _tmp6_;
	gboolean _tmp7_ = FALSE;
	fd_set readfds = {0};
	fd_set writefds = {0};
	fd_set exceptfds = {0};
	struct timeval _tmp8_ = {0};
	struct timeval t;
	struct timeval _tmp9_;
	gint _tmp10_ = 0;
	gint res;
	FsoFrameworkLogger* _tmp11_;
	gboolean _tmp12_ = FALSE;
	FsoFrameworkLogger* _tmp13_;
	gboolean _tmp14_ = FALSE;
	const gchar* _tmp15_;
	self = (LowLevelKernel26_StaysAlive*) base;
	_tmp0_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp1_ = fso_framework_logger_debug (_tmp0_, "Setting power state 'mem'");
	g_assert (_tmp1_);
	_tmp2_ = sys_power_state;
	fso_framework_file_handling_write ("mem\n", _tmp2_, FALSE);
	_tmp3_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp4_ = fso_framework_logger_debug (_tmp3_, "Grabbing input nodes");
	g_assert (_tmp4_);
	_tmp5_ = open ("/dev/input/event3", O_RDONLY, (mode_t) 0);
	fd = _tmp5_;
	ioctl (fd, EVIOCGRAB, 1);
	_tmp6_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp7_ = fso_framework_logger_debug (_tmp6_, "Waiting for action on input node");
	g_assert (_tmp7_);
	memset (&readfds, 0, sizeof (fd_set));
	memset (&writefds, 0, sizeof (fd_set));
	memset (&exceptfds, 0, sizeof (fd_set));
	FD_SET (fd, &readfds);
	_tmp8_.tv_sec = (time_t) ((60 * 60) * 24);
	_tmp8_.tv_usec = (glong) 0;
	t = _tmp8_;
	_tmp9_ = t;
	_tmp10_ = select (fd + 1, &readfds, &writefds, &exceptfds, &_tmp9_);
	res = _tmp10_;
	_tmp11_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp12_ = fso_framework_logger_debug (_tmp11_, "ACTION! Ungrabbing input nodes");
	g_assert (_tmp12_);
	ioctl (fd, EVIOCGRAB, 0);
	_tmp13_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp14_ = fso_framework_logger_debug (_tmp13_, "Setting power state 'on'");
	g_assert (_tmp14_);
	_tmp15_ = sys_power_state;
	fso_framework_file_handling_write ("on\n", _tmp15_, FALSE);
}


static FsoUsageResumeReason low_level_kernel26_staysalive_real_resume (FsoUsageLowLevel* base) {
	LowLevelKernel26_StaysAlive * self;
	FsoUsageResumeReason result = 0;
	self = (LowLevelKernel26_StaysAlive*) base;
	result = FSO_USAGE_RESUME_REASON_Unknown;
	return result;
}


void low_level_kernel26_staysalive_onInput (LowLevelKernel26_StaysAlive* self, void* data, gssize length) {
	FsoFrameworkLogger* _tmp0_;
	FsoFrameworkLogger* _tmp1_;
	gboolean _tmp2_ = FALSE;
	gint _tmp3_;
	FsoFrameworkLogger* _tmp4_;
	gboolean _tmp5_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = ((FsoFrameworkAbstractObject*) self)->logger;
	fso_framework_logger_info (_tmp0_, "Received wakeup request... waking up");
	_tmp1_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp2_ = fso_framework_logger_debug (_tmp1_, "Ungrabbing input nodes");
	g_assert (_tmp2_);
	_tmp3_ = self->priv->fd;
	ioctl (_tmp3_, EVIOCGRAB, 0);
	_tmp4_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp5_ = fso_framework_logger_debug (_tmp4_, "Destroying reactor");
	g_assert (_tmp5_);
}


LowLevelKernel26_StaysAlive* low_level_kernel26_staysalive_construct (GType object_type) {
	LowLevelKernel26_StaysAlive * self = NULL;
	self = (LowLevelKernel26_StaysAlive*) fso_framework_abstract_object_construct (object_type);
	return self;
}


LowLevelKernel26_StaysAlive* low_level_kernel26_staysalive_new (void) {
	return low_level_kernel26_staysalive_construct (LOW_LEVEL_TYPE_KERNEL26_STAYSALIVE);
}


static GObject * low_level_kernel26_staysalive_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	LowLevelKernel26_StaysAlive * self;
	FsoFrameworkLogger* _tmp0_;
	FsoFrameworkSmartKeyFile* _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* sysfs_root;
	const gchar* _tmp3_;
	gchar* _tmp4_ = NULL;
	const gchar* _tmp5_;
	parent_class = G_OBJECT_CLASS (low_level_kernel26_staysalive_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = LOW_LEVEL_KERNEL26_STAYSALIVE (obj);
	_tmp0_ = ((FsoFrameworkAbstractObject*) self)->logger;
	fso_framework_logger_info (_tmp0_, "Registering kernel26_staysalive low level suspend/resume handling");
	_tmp1_ = ((FsoFrameworkAbstractObject*) self)->config;
	_tmp2_ = fso_framework_smart_key_file_stringValue (_tmp1_, "cornucopia", "sysfs_root", "/sys");
	sysfs_root = _tmp2_;
	_tmp3_ = sysfs_root;
	_tmp4_ = g_build_filename (_tmp3_, "power", "state", NULL);
	_g_free0 (sys_power_state);
	sys_power_state = _tmp4_;
	_tmp5_ = sys_power_state;
	fso_framework_file_handling_write ("on\n", _tmp5_, FALSE);
	_g_free0 (sysfs_root);
	return obj;
}


static void low_level_kernel26_staysalive_class_init (LowLevelKernel26_StaysAliveClass * klass) {
	low_level_kernel26_staysalive_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LowLevelKernel26_StaysAlivePrivate));
	FSO_FRAMEWORK_ABSTRACT_OBJECT_CLASS (klass)->repr = low_level_kernel26_staysalive_real_repr;
	G_OBJECT_CLASS (klass)->constructor = low_level_kernel26_staysalive_constructor;
	G_OBJECT_CLASS (klass)->finalize = low_level_kernel26_staysalive_finalize;
}


static void low_level_kernel26_staysalive_fso_usage_low_level_interface_init (FsoUsageLowLevelIface * iface) {
	low_level_kernel26_staysalive_fso_usage_low_level_parent_iface = g_type_interface_peek_parent (iface);
	iface->suspend = (void (*)(FsoUsageLowLevel*)) low_level_kernel26_staysalive_real_suspend;
	iface->resume = (FsoUsageResumeReason (*)(FsoUsageLowLevel*)) low_level_kernel26_staysalive_real_resume;
}


static void low_level_kernel26_staysalive_instance_init (LowLevelKernel26_StaysAlive * self) {
	self->priv = LOW_LEVEL_KERNEL26_STAYSALIVE_GET_PRIVATE (self);
}


static void low_level_kernel26_staysalive_finalize (GObject* obj) {
	LowLevelKernel26_StaysAlive * self;
	self = LOW_LEVEL_KERNEL26_STAYSALIVE (obj);
	G_OBJECT_CLASS (low_level_kernel26_staysalive_parent_class)->finalize (obj);
}


GType low_level_kernel26_staysalive_get_type (void) {
	return low_level_kernel26_staysalive_type_id;
}


GType low_level_kernel26_staysalive_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (LowLevelKernel26_StaysAliveClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) low_level_kernel26_staysalive_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LowLevelKernel26_StaysAlive), 0, (GInstanceInitFunc) low_level_kernel26_staysalive_instance_init, NULL };
	static const GInterfaceInfo fso_usage_low_level_info = { (GInterfaceInitFunc) low_level_kernel26_staysalive_fso_usage_low_level_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	low_level_kernel26_staysalive_type_id = g_type_module_register_type (module, FSO_FRAMEWORK_TYPE_ABSTRACT_OBJECT, "LowLevelKernel26_StaysAlive", &g_define_type_info, 0);
	g_type_module_add_interface (module, low_level_kernel26_staysalive_type_id, FSO_USAGE_TYPE_LOW_LEVEL, &fso_usage_low_level_info);
	return low_level_kernel26_staysalive_type_id;
}


/**
 * This function gets called on plugin initialization time.
 * @return the name of your plugin here
 * @note that it needs to be a name in the format <subsystem>.<plugin>
 * else your module will be unloaded immediately.
 **/
gchar* fso_factory_function (FsoFrameworkSubsystem* subsystem, GError** error) {
	gchar* result = NULL;
	FsoFrameworkLogger* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (subsystem != NULL, NULL);
	_tmp0_ = fso_framework_theLogger;
	fso_framework_logger_debug (_tmp0_, "lowlevel_kernel26_staysalive fso_factory_function");
	_tmp1_ = g_strdup ("fsousage.lowlevel_kernel26_staysalive");
	result = _tmp1_;
	return result;
}


void fso_register_function (GTypeModule* module) {
	g_return_if_fail (module != NULL);
	low_level_kernel26_staysalive_register_type (module);
}



